services:
  postgresql:
    image: postgres:14.9
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: link-shortener
      POSTGRES_PASSWORD: password
      POSTGRES_DB: link-shortener
    healthcheck:
      test: [ "CMD", "psql", "postgresql://link-shortener:password@localhost:5432/link-shortener", "-c", "select 1;" ]
      interval: 5s
      timeout: 5s
      retries: 3
    command: [ "postgres", "-c", "log_statement=all" ]
