CREATE TABLE IF NOT EXISTS "user"(
  id BIGINT PRIMARY KEY,
  email VARCHAR NOT NULL,
  email_hash VARCHAR NOT NULL,
  password VARCHAR NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_user_email ON "user"(email_hash);
CREATE SEQUENCE IF NOT EXISTS user_id_seq START 1 INCREMENT 50;